version: '3.8'

services:
  # ===========================================
  # INFRASTRUCTURE SERVICES
  # ===========================================
  
  # MySQL Database for AuthService
  auth-db:
    image: mysql:8.0
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./authservice/src/main/resources/db_migration.sql:/docker-entrypoint-initdb.d/migration.sql
    networks:
      backend-network:
#        ipv4_address: 172.16.0.40
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # MySQL Database for UserService
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_db
      MYSQL_USER: user_user
      MYSQL_PASSWORD: user_pass
    volumes:
      - user_db_data:/var/lib/mysql
    networks:
      backend-network:
#        ipv4_address: 172.16.0.41
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # MySQL Database for WorkoutService
  workout-db:
    image: mysql:8.0
    container_name: workout-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: workout_db
      MYSQL_USER: workout_user
      MYSQL_PASSWORD: workout_pass
    volumes:
      - workout_db_data:/var/lib/mysql
    networks:
      backend-network:
#        ipv4_address: 172.16.0.42
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # MySQL Database for MealService
  meal-db:
    image: mysql:8.0
    container_name: meal-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: meal_db
      MYSQL_USER: meal_user
      MYSQL_PASSWORD: meal_pass
    volumes:
      - meal_db_data:/var/lib/mysql
    networks:
      backend-network:
        # ipv4_address: 172.16.0.43
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # MySQL Database for AnalystService
  analyst-db:
    image: mysql:8.0
    container_name: analyst-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: analyst_db
      MYSQL_USER: analyst_user
      MYSQL_PASSWORD: analyst_pass
    volumes:
      - analyst_db_data:/var/lib/mysql
    networks:
      backend-network:
        # ipv4_address: 172.16.0.44
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      backend-network:
        # ipv4_address: 172.16.0.50
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  # ===========================================
  # DISCOVERY SERVER
  # ===========================================
  
  discovery-server:
    build:
      context: ./discoveryserver
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      backend-network:
        # ipv4_address: 172.16.0.10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # APIService (Gateway) - Instance 1
  api-service-1:
    build:
      context: ./apiservice
      dockerfile: Dockerfile
    container_name: api-service-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=8080
      - EUREKA_INSTANCE_HOSTNAME=api-service-1
    depends_on:
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      backend-network:
        # ipv4_address: 172.16.0.20
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # APIService (Gateway) - Instance 2
  api-service-2:
    build:
      context: ./apiservice
      dockerfile: Dockerfile
    container_name: api-service-2
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=8080
      - EUREKA_INSTANCE_HOSTNAME=api-service-2
    depends_on:
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      backend-network:
        # ipv4_address: 172.16.0.21
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # ===========================================
  # LOAD BALANCER
  # ===========================================

 # HAProxy Load Balancer
  haproxy:
   build:
     context: ./haproxy
     dockerfile: Dockerfile
   container_name: haproxy
   ports:
     - "80:80"
     - "8443:443"
     - "8403:8403"
     - "8404:8404"
   volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
     - ./ssl:/usr/local/etc/haproxy/ssl:ro
     - /tmp/haproxy:/var/run
   depends_on:
     api-service-1:
       condition: service_healthy
     api-service-2:
       condition: service_healthy
     discovery-server:
       condition: service_healthy
   networks:
     backend-network:
       # ipv4_address: 172.16.0.100
   restart: unless-stopped
   healthcheck:
     test: ["CMD", "wget", "--quiet", "--spider", "http://127.0.0.1:80/actuator/health"]
     interval: 10s
     timeout: 5s
     retries: 5
     start_period: 30s

  # ===========================================
  # MICROSERVICES
  # ===========================================

  # AuthService
  auth-service:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth-db:3306/auth_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=auth_user
      - SPRING_DATASOURCE_PASSWORD=auth_pass
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      auth-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      api-service-1:
        condition: service_healthy
      api-service-2:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      backend-network:
        # ipv4_address: 172.16.0.30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # UserService
  user-service:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/user_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user_user
      - SPRING_DATASOURCE_PASSWORD=user_pass
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVICES_AUTHSERVICE_URL=http://auth-service:8005
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      user-db:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      backend-network:
        # ipv4_address: 172.16.0.31
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # WorkoutService
  workout-service:
    build:
      context: ./workoutservice
      dockerfile: Dockerfile
    container_name: workout-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://workout-db:3306/workout_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=workout_user
      - SPRING_DATASOURCE_PASSWORD=workout_pass
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVICES_USERSERVICE_URL=http://user-service:8006
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      workout-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      backend-network:
        # ipv4_address: 172.16.0.32
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # MealService
  meal-service:
    build:
      context: ./mealservice
      dockerfile: Dockerfile
    container_name: meal-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://meal-db:3306/meal_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=meal_user
      - SPRING_DATASOURCE_PASSWORD=meal_pass
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVICES_USERSERVICE_URL=http://user-service:8006
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      meal-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      backend-network:
        # ipv4_address: 172.16.0.33
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # AnalystService
  analyst-service:
    build:
      context: ./analystservice
      dockerfile: Dockerfile
    container_name: analyst-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://analyst-db:3306/analyst_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=analyst_user
      - SPRING_DATASOURCE_PASSWORD=analyst_pass
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVICES_USERSERVICE_URL=http://user-service:8006
      - SERVICES_WORKOUTSERVICE_URL=http://workout-service:8007
      - SERVICES_MEALSERVICE_URL=http://meal-service:8008
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      analyst-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
      meal-service:
        condition: service_healthy
      workout-service:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      backend-network:
        #ipv4_address: 172.16.0.34
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

# ===========================================
# NETWORKS
# ===========================================
networks:
  backend-network:
    driver: bridge
    name: health-app-network
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1

# ===========================================
# VOLUMES
# ===========================================
volumes:
  auth_db_data:
    name: auth_db_data
  user_db_data:
    name: user_db_data
  workout_db_data:
    name: workout_db_data
  meal_db_data:
    name: meal_db_data
  analyst_db_data:
    name: analyst_db_data
  redis_data:
    name: redis_data 